"""Builds AbilityDraft/AbilityPool.g.cs from the user's own Deadlock install.

Inputs (never shipped): decompiled scripts/heroes.vdata + scripts/abilities.vdata (see tools/dump-vdata.ps1)
and the loose localization files in game/citadel/resource/localization.
Usage: python gen_pool.py <dump dir> <Deadlock dir> <out .cs>
"""
import io, re, sys

dump, game, out = sys.argv[1:4]
heroes = open(f"{dump}/heroes.vdata", encoding="utf-8").read()
abil = open(f"{dump}/abilities.vdata", encoding="utf-8").read()


def loc(folder, lang):
    path = f"{game}/game/citadel/resource/localization/{folder}/{folder}_{lang}.txt"
    try:
        raw = open(path, "rb").read()
    except OSError:
        return {}
    text = raw.decode("utf-16") if raw[:2] in (b"\xff\xfe", b"\xfe\xff") else raw.decode("utf-8-sig", "replace")
    return {k.lower(): v for k, v in re.findall(r'^\s*"([^"]+)"\s+"((?:[^"\\]|\\.)*)"', text, re.M)}


names = {lang: {**loc("citadel_gc_hero_names", lang), **loc("citadel_gc", lang), **loc("citadel_heroes", lang)}
         for lang in ("english", "russian")}


def blocks(text):
    parts = re.split(r"\n\t(?=[A-Za-z_0-9]+ = \n\t\{)", text)
    return {m.group(1): p for p in parts if (m := re.match(r"([A-Za-z_0-9]+) = ", p))}


def field(block, key):
    m = re.search(r"\n\t\t" + key + r' = (?:panorama:)?"?([^"\n]+)"?', block)
    return m.group(1) if m else ""


def cs(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


UNRELEASED = {"hero_baba"}
ab = blocks(abil)
rows = []
skipped = []
for hero, b in blocks(heroes).items():
    if not hero.startswith("hero_") or hero in ("hero_base", "hero_targetdummy", "hero_genericperson"):
        continue
    # Heroes still in development are left out - except the ones named here, whose abilities are wanted in the
    # draft anyway. They are not playable heroes, only a source of abilities.
    if field(b, "m_bDisabled") == "true" or field(b, "m_bInDevelopment") == "true" and hero not in UNRELEASED:
        continue
    sig = [m.group(1) if (m := re.search(r'ESlot_Signature_%d = "([^"]+)"' % i, b)) else None for i in range(1, 5)]
    if None in sig:
        skipped.append(hero)
        continue
    en = names["english"].get(hero + ":n", hero[5:].title())
    ru = re.sub(r"^#\|\w\|#", "", names["russian"].get(hero + ":n", en))
    for i, a in enumerate(sig):
        blk = ab.get(a, "")
        ult = "Ultimate" in field(blk, "m_eAbilityType")
        rows.append((hero, en, ru, i + 1, a, names["english"].get(a, a), names["russian"].get(a, names["english"].get(a, a)),
                     ult, field(blk, "m_strAbilityImage")))

with io.open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("// <auto-generated> tools/gen_pool.py - names and ids only, read from the local Deadlock install. </auto-generated>\n")
    f.write("namespace AbilityDraft;\n\npublic static partial class AbilityPool\n{\n    public static readonly AbilityDef[] All =\n    [\n")
    for r in rows:
        f.write("        new(%s, %s, %s, %d, %s, %s, %s, %s, %s),\n" % (
            cs(r[0]), cs(r[1]), cs(r[2]), r[3], cs(r[4]), cs(r[5]), cs(r[6]), "true" if r[7] else "false", cs(r[8])))
    f.write("    ];\n\n    // Heroes that cannot be picked yet; only their abilities are in the pool.\n")
    f.write("    public static readonly string[] Unreleased = [%s];\n}\n" % ", ".join(cs(h) for h in sorted(UNRELEASED)))
print(f"{len(rows)} abilities from {len(rows)//4} heroes; skipped (no kit): {skipped}")
